name: mern-app

services:
  mongo:
    image: mongo:7.0.12
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - mern-app

  api:
    build:
      context: ./server
      dockerfile: Dockerfile

    restart: unless-stopped
    env_file: ./server/.env

    volumes:
      - ./server:/app
      - /app/node_modules

    networks:
      - mern-app

    ports:
      - "8082:8082"

volumes:
  mongo_data:
  caddy_data:
  caddy_config:
networks:
  mern-app:
    driver: bridge
