name: mern-app

services:
  mongo:
    image: mongo:7.0.12
    volumes:
      - mongo_data:/data/db
    networks:
      - mern-app

  api:
    build:
      context: ./server
      target: development

    restart: unless-stopped
    env_file: ./server/.env

    networks:
      - mern-app

  frontend:
    build:
      context: ./client
      target: development
      args:
        VITE_API_URL: http://api.auth.localhost
        VITE_CLIENT_URL: http://auth.localhost
    restart: unless-stopped
    env_file: ./client/.env

    volumes:
      - ./client:/app
      - /app/node_modules

    networks:
      - mern-app

    command: npm run dev -- --host

    depends_on:
      - api

  caddy:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - mern-app
    depends_on:
      - api
      - frontend

volumes:
  mongo_data:
  caddy_data:
  caddy_config:
networks:
  mern-app:
    driver: bridge
